FROM ghcr.io/fnctl/alpine:latest
RUN apk add -u --no-cache bash bat busybox-extras curl doctl file git git-extras github-cli gnupg grep jq kubectl less make mdbook ripgrep sed skopeo terraform unzip vault wget yq zip zola
ENTRYPOINT ["/bin/bash"]
