FROM ghcr.io/fnctl/alpine:latest
RUN apk add -u --no-cache bash bat busybox-extras curl file git git-extras github-cli gnupg grep jq less make mdbook ripgrep sed unzip wget yq zip zola
ENTRYPOINT ["/bin/bash"]
